### ISSUE TITLE
Version 1.1.1 unable to access service account from metadata

### ISSUE THREAD

**Issue by jamesrobson-secondmind** [jenkinsci/google-oauth-plugin#198]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.414.2
OS: Linux - 5.15.0-1044-gcp
Java: 11.0.20.1 - Ubuntu (OpenJDK 64-Bit Server VM)
---
ace-editor:1.1
active-directory:2.33
ansicolor:1.0.4
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
authentication-tokens:1.53.v1c90fd9191a_b_
basic-branch-build-strategies:81.v05e333931c7d
blueocean:1.27.8
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.8
blueocean-commons:1.27.8
blueocean-config:1.27.8
blueocean-core-js:1.27.8
blueocean-dashboard:1.27.8
blueocean-display-url:2.4.2
blueocean-events:1.27.8
blueocean-git-pipeline:1.27.8
blueocean-github-pipeline:1.27.8
blueocean-i18n:1.27.8
blueocean-jira:1.27.8
blueocean-jwt:1.27.8
blueocean-personalization:1.27.8
blueocean-pipeline-api-impl:1.27.8
blueocean-pipeline-editor:1.27.8
blueocean-pipeline-scm-api:1.27.8
blueocean-rest:1.27.8
blueocean-rest-impl:1.27.8
blueocean-web:1.27.8
bootstrap4-api:4.6.0-5
bootstrap5-api:5.3.2-1
bouncycastle-api:2.29
branch-api:2.1128.v717130d4f816
build-environment:1.7
build-failure-analyzer:2.4.2
build-monitor-plugin:1.14-745.ve2023a_305f40
build-pipeline-plugin:1.5.8
build-timeout:1.31
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloudbees-bitbucket-branch-source:848.v42c6a_317eda_e
cloudbees-disk-usage-simple:182.v62ca_0c992a_f3
cloudbees-folder:6.848.ve3b_fd7839a_81
cobertura:1.17
code-coverage-api:4.8.0
command-launcher:100.v2f6722292ee8
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.10.0-78.v3e7b_ea_d5a_fe1
conditional-buildstep:1.4.2
config-file-provider:959.vcff671a_4518b_
configuration-as-code:1714.v09593e830cfa
copyartifact:722.v0662a_9b_e22a_c
credentials:1293.vff276f713473
credentials-binding:636.v55f1275c7b_27
data-tables-api:1.13.6-5
disable-github-multibranch-status:1.2
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:572.v950f58993843
durable-task:523.va_a_22cf15d5e0
echarts-api:5.4.0-6
email-ext:2.102
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
extended-read-permission:3.2
favorite:2.4.3
font-awesome-api:6.4.2-1
forensics-api:2.3.0
git:5.2.0
git-client:4.5.0
github:1.37.3
github-api:1.316-451.v15738eef3414
github-branch-source:1741.va_3028eb_9fd21
google-compute-engine:4.3.17
google-container-registry-auth:0.3
google-oauth-plugin:1.1.1
greenballs:1.15.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
hashicorp-vault-plugin:361.v44fea_4fc08d9
htmlpublisher:1.32
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:66.vd8fa_64ee91b_d
jenkins-design-language:1.27.8
jersey2-api:2.40-1
jira:3.11
jira-steps:2.0.165.v8846cf59f3db
jjwt-api:0.11.5-77.v646c772fddb_0
job-dsl:1.85
jobConfigHistory:1229.v3039470161a_d
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.7.1-1
jsch:0.2.8-65.v052c39de79b_2
junit:1240.vf9529b_881428
kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
kubernetes-credentials:0.9.0
logstash:2.5.0218.v0a_ff8fefc12b_
mailer:463.vedf8358e006b_
matrix-auth:3.2.1
matrix-project:808.v5a_b_5f56d6966
metrics:4.2.18-442.v02e107157925
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
momentjs:1.1.1
oauth-credentials:0.646.v02b_66dc03d2e
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
parameterized-trigger:2.46
pipeline-build-step:505.v5f0844d8d126
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2144.v077a_d1928a_40
pipeline-model-definition:2.2144.v077a_d1928a_40
pipeline-model-extensions:2.2144.v077a_d1928a_40
pipeline-npm:95.v5213efa_9585f
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2144.v077a_d1928a_40
pipeline-stage-view:2.33
pipeline-utility-steps:2.16.0
plain-credentials:143.v1b_df8b_d3b_e48
plot:2.1.12
plugin-util-api:3.4.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
prism-api:1.29.0-8
prometheus:2.3.3
pubsub-light:1.17
pyenv-pipeline:2.1.2
resource-disposer:0.23
reverse-proxy-auth-plugin:1.7.7
run-condition:1.5
scm-api:676.v886669a_199a_a_
script-security:1275.v23895f409fb_d
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
sse-gateway:1.26
ssh-agent:333.v878b_53c89511
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
sshd:3.303.vefc7119b_ec23
structs:325.vcb_307d2a_2782
timestamper:1.26
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
variant:60.v7290fc0eb_b_cd
view-job-filters:369.ve0513a_a_f5524
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3802.vd42b_fcf00b_a_c
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1348.v32a_a_f150910e
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

1. Have a `Google Service Account from Metadata` used to authenticate with GCP to start agents using [google compute engine plugin](https://plugins.jenkins.io/google-compute-engine)
2. install version 1.1.1
3. Attempt to create an agent

### Expected Results

Agent is created normally

### Actual Results

Agent is not created and the following stack trace is recorded
```
Oct 09 07:50:11 jenkins-dev jenkins[1692]: hudson.AbortException: Failed to initialize HTTP transport: hudson.AbortException: Could not retrieve credentials: <cred id>
Oct 09 07:50:11 jenkins-dev jenkins[1692]:         at com.google.jenkins.plugins.computeengine.client.ClientUtil.getClientFactory(ClientUtil.java:56)
Oct 09 07:50:11 jenkins-dev jenkins[1692]:         at com.google.jenkins.plugins.computeengine.client.ClientUtil.getClientFactory(ClientUtil.java:71)
Oct 09 07:50:11 jenkins-dev jenkins[1692]:         at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.createClient(ComputeEngineCloud.java:190)
Oct 09 07:50:11 jenkins-dev jenkins[1692]:         at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.getClient(ComputeEngineCloud.java:208)
Oct 09 07:50:11 jenkins-dev jenkins[1692]:         at com.google.jenkins.plugins.computeengine.InstanceConfiguration.instance(InstanceConfiguration.java:384)
Oct 09 07:50:11 jenkins-dev jenkins[1692]:         at com.google.jenkins.plugins.computeengine.InstanceConfiguration.provision(InstanceConfiguration.java:305)
Oct 09 07:50:11 jenkins-dev jenkins[1692]:         at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.doProvision(ComputeEngineCloud.java:435)
...
```

### Anything else?

Downgrading to version 1.0.11 of this plugin resolved the problem.

**Comment by vlad-ivanov-name** [comment]
This issue also occurs with accounts from private keys.

**Comment by vlad-ivanov-name** [comment]
The offending commit is https://github.com/jenkinsci/google-oauth-plugin/commit/04863b711393f91a861b057eecaf96f6fc226360

The way it's implemented makes the credential ID change every time Jenkins starts making it impossible to reference the secret from anywhere

**Comment by vlad-ivanov-name** [comment]
Worst of all, even on the latest version ID gets overridden upon restart even with ID set manually 🤯

**Comment by vlad-ivanov-name** [comment]
Figured it out.

Previously the way credential ID was implemented would create an export for CasC like this:

```
"credentials":
  "system":
    "domainCredentials":
    - "credentials":
      - "googleRobotMetadata":
          "projectId": "project"
```

This would then be applied to one of the credential class constructors as follows:

![CleanShot 2024-01-04 at 15 05 39](https://github.com/jenkinsci/google-oauth-plugin/assets/2057191/f6ce6c7b-0a5c-4bb2-85d4-6703766dfdaa)

With the newer versions of the plugin, this means every time Jenkins starts and CasC is applied, ID is updated because it's `null`, and therefore becomes randomly generated.

So a fixed CasC entry would look like this:

```
"credentials":
  "system":
    "domainCredentials":
    - "credentials":
      - "googleRobotMetadata":
          "id": "project"
          "projectId": "project"
```

**Comment by jamesrobson-secondmind** [comment]
Confirmed that adding ID to the CasC definition fixes the issue.
